config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  # Static pages
  get 'mobile' => 'pages#mobiles'
  get '/report' => 'pages#report'
  get '/contact' => 'pages#contact'
  get '/reglas' => 'pages#rules'
  get '/nosotros' => 'pages#about'
  get '/match_info' => 'matches#match_info'
  get '/live_matches' => 'home#live_matches'

  # Seasons
  get '/seasons/0' => 'pages#season0'

  # User list
  get 'users', to: 'users#index'

  resources :match_tokens, only: [:edit, :update]
  resources :matches do
    member do
      get :join
      post :leave
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks', :registrations => 'registrations' }

  get 'user/:username' => 'users#show', constraints: { username: /[^:]+/ }
  get 'users/:username' => 'users#show', constraints: { username: /[^:]+/ }, as: 'user'
  put 'users/:id' => 'users#update', constraints: { username: /[^:]+/ }
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  layout 'home'

  before_action :sidebar_stats
  def index
    @stats = { match_count: Match.where(status: 'ended').count,
               user_count: User.count,
               last_match: Match.last.created_at.strftime('%d/%m/%Y')
              } if Match.all.any?

    leaders = User.league_leaders if User.all.any?
    @leaders = UserDecorator.decorate_collection(leaders)
    latest_matches = Match.live
    @latest_matches = latest_matches.decorate
  end

  def live_matches
    latest_matches = Match.live
    @latest_matches = latest_matches.decorate

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def sidebar_stats
    @sidebar_stats = {
      most_wins: User.most_wins,
      most_captains: User.most_captains,
      most_creations: User.most_creations
    } if User.all.any?
  end
end

app/views/home/_live_matches.haml
- if @latest_matches.empty?
  .centered= "No hay matches en vivo, #{link_to 'Crea un Lobby!', new_match_path}".html_safe
- else
  - @latest_matches.each do |match|
    = link_to(match_path(match))do
      %li
        .title
          %span.designation
            = match.name
            %br
              = match.created_at.strftime("Creada %m/%d/%Y - %I:%M%p")
        .streak= match.pretty_status
        .rating= match.action(current_user)

app/views/home/index.haml
%section.header-area
  = render 'layouts/main_menu'
  .banner-slider
    %ul.slides.clearfix
      %li= image_tag('banner-05.jpg')
      %li= image_tag('banner-01.jpg')
      %li= image_tag('banner-04.jpg')
      %li= image_tag('banner-03.jpg')
      %li= image_tag('banner-02.jpg')
  .banner-cont-wrapper
    .container
      .logo-area
        = image_tag('ddl-logo-white.png', style: 'width: 320px; height:237px; margin-top: 100px;' )
        %h1{style: 'color: white; -webkit-text-stroke: 1px black; font-size: 25px; padding: 0px;   text-shadow:-1px -1px 0 #000,1px -1px 0 #000,-1px 1px 0 #000, 1px 1px 0 #000;);'} Ranking de in-houses dominicanos de ultima generacion
      .banner-conts
        .post-job
          - if current_user
            = link_to('Ver juegos', matches_path, class: 'post-job-btn shadow-1')
          - else
            = link_to('Registrate', new_user_registration_path, class: 'post-job-btn')
  = render ('layouts/login_box') unless user_signed_in?
%section.live-leaderboards
  .container
    .row
      .col-md-10
        %h3.pull-left LIVE GAMES
        .pull-right.pt-15
          = link_to('crear +', new_match_path, {class: 'action-button-orange', style: 'display: inline;' }) if current_user && current_user.can_create_games?
          = link_to('ver juegos', matches_path, {class: 'action-button-blue', style: 'display: inline;' })
        .clearfix
        .job-list-head.clearfix{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
          .title Nombre
          .location Status
          .created Acción
        %ul.job-listings
          #match-data
            = render 'live_matches'
        %h3.pull-left LEADERS
        .pull-right.pt-15
          = link_to('ver usuarios', users_path, {class: 'action-button-blue', style: 'display: inline;' })
        %table#user-table.table.table-striped.user-table
          %thead
            %tr
              %th Pos
              %th Nombre
              %th W/L
              %th Juegos
              %th Rating
          %tbody.leaderboard-content
            - @leaders.each_with_index do |player, position|
              %tr{ class: player.position_table_class(position) }
                %td.position.post{style: 'text-align: center;'}= position + 1
                %td
                  - if current_user && current_user.id == player.id
                    = link_to(player.name, "/user/#{player.regular_name}", style: 'color: black; font-size: 20px;')
                  - else
                    = link_to(player.name, "/user/#{player.regular_name}")
                  %br
                  %i= player.real_name
                %td.i-info= player.wins_and_losses
                %td.i-info= player.games_count
                %td.i-info= player.rating
      .col-md-2{style: 'margin-top: -3px;'}
        = render ('layouts/stats_sidebar')
- unless @stats.nil?
  %section.job-statistics-main
    .container
      %h3{"data-animation" => "fadeInUp", "data-animation-delay" => "100"} league statistics
      %h5.uppercase{"data-animation" => "fadeInUp", "data-animation-delay" => "200"} DATOS GENERALES
      %hr
        %ul.statistic-val
          %li.animated{"data-animation" => "flipInY", "data-animation-delay" => "200"}
            = link_to(matches_path, style: 'color: black !important; text-decoration: none;') do
              .stastic-single
                .ico-conts
                  %span= @stats[:match_count]
                  %i.fi-heart
                %h7 Partidas finalizadas
          %li.animated{"data-animation" => "flipInY", "data-animation-delay" => "400"}
            = link_to(matches_path, style: 'color: black !important; text-decoration: none;') do
              .stastic-single
                .ico-conts
                  %span= @stats[:last_match]
                  %i.fi-address-book
              %h7  Última partida
          %li.animated{"data-animation" => "flipInY", "data-animation-delay" => "1000"}
            = link_to(users_path, style: 'color: black !important; text-decoration: none;') do
              .stastic-single
                .ico-conts
                  %span= @stats[:user_count]
                  %i.fi-torso-business
                %h7 Miembros
%section.got-a-question
  .container
    .row.clearfix
      .col-md-3.call-us-head.animated{"data-animation" => "fadeInLeft", "data-animation-delay" => "200", style: 'margin-top: -50px;'}
        .col-md-offset-3= image_tag('stomp-logo.png', {style: 'width: 100px; height: 100px'})
        %h2 STOMP MACHINE
      .col-md-6.call-us-txt{"data-animation" => "fadeInUp", "data-animation-delay" => "300"}
        %p Síguenos en Facebook para mantenerte enterado sobre la plataforma!
      .col-md-3.call-us-link.animated{"data-animation" => "fadeInRight", "data-animation-delay" => "200"}
        %a.call-us-btn{:href => 'https://www.facebook.com/thestompmachine', target: '_blank'} NUESTRO FACEBOOK

:javascript
  $( document ).ready(function() {
    // Refresh match pool every 5 seconds.
    setInterval(refreshPartial, 5000);
    function refreshPartial() {
      $.ajax({
        url: "/live_matches"
     })
    }
    $('#user-table').DataTable({
      "bAutoWidth": false
      "aoColumns" : [ { sWidth: "15%" }, { sWidth: "20%" }, { sWidth: "25%" }, { sWidth: "15%" }, { sWidth: "20%" }],
      "bPaginate": false,
      "showNEntries": false,
      "bInfo":false,
       responsive: true
    });
  });

app/views/home/live_matches.js.erb
$('#match-data').html("<%= escape_javascript(render(:partial => 'live_matches')) %>");
jQuery(document).ready(function($) {
  $('a[data-popup*=facebox]').facebox({
    opacity      : 0.9,
    loadingImage : '',
    closeImage   : ''
  })
})