config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  # Static pages
  get 'mobile' => 'pages#mobiles'
  get '/report' => 'pages#report'
  get '/contact' => 'pages#contact'
  get '/reglas' => 'pages#rules'
  get '/nosotros' => 'pages#about'
  get '/match_info' => 'matches#match_info'
  get '/live_matches' => 'home#live_matches'

  # Seasons
  get '/seasons/0' => 'pages#season0'

  # User list
  get 'users', to: 'users#index'

  resources :match_tokens, only: [:edit, :update]
  resources :matches do
    member do
      get :join
      post :leave
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks', :registrations => 'registrations' }

  get 'user/:username' => 'users#show', constraints: { username: /[^:]+/ }
  get 'users/:username' => 'users#show', constraints: { username: /[^:]+/ }, as: 'user'
  put 'users/:id' => 'users#update', constraints: { username: /[^:]+/ }
end

app/models/match.rb
# Match class, models a match (game) in the league, a match starts empty and
# finishes with 10 players, 2 teams (one winner and one loser).
class Match < ActiveRecord::Base
  has_many :teams
  has_many :match_tokens
  has_many :users, through: :match_tokens

  default_scope { order('created_at DESC') }
  scope :live, -> { where('status = ? or status = ?', 'waiting', 'playing') }

  # Checks if match is being played at the moment.
  def playing?
    status == 'playing'
  end

  # Checks if match has ended.
  def ended?
    status == 'ended'
  end

  # Checks if  match is canceled.
  def canceled?
    status == 'canceled'
  end

  # Checks if match is leaveable at the moment.
  def leavable?
    status != 'playing' && status != 'ended'
  end

  # Checks if match is joinable by players/waiting for players.
  def joinable?
    status == 'waiting'
  end
  alias_method :waiting?, :joinable?

  # Calculates the number of result votes a match has.
  def votes_number
    match_tokens.select { |token| token.result.present? }.count
  end

  def enough_vote_frequency?
    freq = Hash.new(0)
    voted_results = match_tokens.map(&:result)
    voted_results.each { |v| freq[v] += 1 }
    freq['radiant'] >= 6 || freq['canceled'] >= 6 || freq['dire'] >= 6 ? true : false
  end

  def vote_frequency
    freq = Hash.new(0)
    voted_results = match_tokens.map(&:result)
    voted_results.each { |v| freq[v] += 1 }
    freq
  end

  # If the match hasn't been canceled, has started but hasn't ended, and it has more than
  # 6 votes with the same result it's commitable (commit: save the result and end it).
  def committable?(freq = {})
    return false if status == 'ended' || status == 'canceled'
    enough_vote_frequency?
  end

  # Starts a match, creates the teams and changes status to playing
  # if enough Users have joined the match (10 Users).
  def start
    return false if match_tokens.count != 10
    create_teams
    self.status = 'playing'
    self.save!
  end

  # Cancels a match and unties Users from it.
  def cancel
    return false if playing? && votes_number < 6
    self.status = 'canceled'
    self.winner_team = nil

    match_tokens.destroy_all
    self.save!
  end

  # Interface to create balanced teams.
  def create_teams
    # Get relevant players data and balance for team creation.
    players_pool = users.pluck(:user_id, :rating)
    balanced_teams_hash = balance_players(players_pool)

    # Create real teams for match with the balanced team hash.
    Team.create_for_match(balanced_teams_hash, id)
    save_users_and_attributes(:id, :name, :rating, :status,
                              :facebook_link, :donator,
                              :win_count, :lose_count)
  end

  # Balance interface (team distribution).
  def balance_players(players_pool_array)
    @balanced = false
    @min_separation = 3
    @shuffles = 0

    while @balanced == false
      players_pool_array.shuffle!
      @shuffles += 1
      distribute_players players_pool_array

      check_separation @radiant_avg, @dire_avg, @min_separation
    end

    assign_teams @radiant_array, @dire_array
  end

  # Distributes players between radiant and dire from a shuffled player array.
  def distribute_players(players_pool_array)
    @radiant_array, @radiant_avg = players_pool_array.first(5), 0
    @dire_array, @dire_avg = players_pool_array.last(5), 0

    @radiant_array.each { |player| @radiant_avg += player[1] }
    @dire_array.each { |player| @dire_avg += player[1] }
  end

  # Checks if team rating averages meet minimum separation, if not reshuffles,
  # additionally, checks if if it's needed to increase the minimun separation.
  def check_separation(radiant_avg, dire_avg, min_separation)
    if (radiant_avg - dire_avg).abs < min_separation
      @balanced = true
    else
      @balanced = false
      if @shuffles > 1000
        @min_separation += 3
        @shuffles = 0
      end
    end
  end

  # Assigns the players to a temp team hash in order to create the real teams.
  def assign_teams(radiant_array, dire_array)
    dire = []
    radiant = []
    radiant_array.each { |player| radiant << User.find(player.first) }
    dire_array.each { |player| dire << User.find(player.first) }

    { radiant: radiant, dire: dire }
  end

  # Saves frozen user attributes for future reference i.e: actual rating at the
  # time the match happened.
  def save_users_and_attributes(*stats)
    players_pool_with_stats = users.select(stats)
    self.users_and_stats = players_pool_with_stats.as_json
  end

  # Commit and finalize the Match if enough votes have been processed.
  # 6 votes is enough to declare a winner.
  def commit
    return false unless committable?
    result = vote_frequency.reject { |_k, v| v < 6 }.keys.first
    if result == 'radiant' || result == 'dire'
      winner_team = teams.where(side: result)
      loser_team = (teams - winner_team).first
      winner_team = winner_team.first

      update_player_stats(winner_team, loser_team, result)
      finalize_match(result)
    else
      cancel
    end
  end

  # Updates Users stats depending on the match result.
  def update_player_stats(winner_team, loser_team, result)
    # Update win counts
    users.each { |u| update_user_game_result_count(u, winner_team) }

    # Check how much player rating going to change.
    rating_change = calculate_rating_change(winner_team, loser_team)

    if result == 'radiant'
      users.each { |u| update_user_rating(u, winner_team, rating_change, 'dire') }
    else
      users.each { |u| update_user_rating(u, winner_team, rating_change, 'radiant') }
    end
  end

  # Calculates how much the rating should change depending on who won.
  def calculate_rating_change(winner_team, loser_team)
    (Team.rating_change((winner_team.users.sum(:rating) / 5),
                        (loser_team.users.sum(:rating) / 5)))
  end

  # Updates win/loss count for user.
  def update_user_game_result_count(user, winner_team)
    if winner_team.users.include? user
      user.win_count += 1
    else
      user.lose_count += 1
    end
    user.save!
  end

  # Updates rating for users depending on which team they were.
  def update_user_rating(user, winner_team, rating_change, rating_change_name)
    if winner_team.users.include? user
      new_rating = user.rating + rating_change[rating_change_name.to_sym]
      user.rating = new_rating
    else
      new_rating = user.rating - rating_change[rating_change_name.to_sym]
      user.rating = new_rating
    end
    user.save!
  end

  # Saves match result information for teams and sets "ended" status.
  def finalize_match(result)
    if result == 'radiant'
      self.winner_team = false
    elsif result == 'dire'
      self.winner_team = true
    end
    match_tokens.each { |t| t.result = winner_team; t.save! }

    self.status = 'ended'
    self.save!
  end
end

app/controllers/matches_controller.rb
class MatchesController < ActionController::Base
  layout 'application'

  before_action :authenticate_user!, except: [:show, :index, :match_info]
  before_action -> { establish_match_entities Match.find(params[:id]) },
                only: [:show, :match_info]

  def index
    matches = Match.all
    @matches = matches.decorate

    respond_to do |format|
      format.html
      format.json { render json: @matches }
    end
  end

  def show
    match = Match.find(params[:id])
    @match = match.decorate

    @match_token = MatchToken.from_user_and_match(current_user, params[:id]) \
    if current_user && current_user.in_match?(@match.id)
    (@rating_change = Team.rating_change(@radiant_team_avg, @dire_team_avg)) \
    if @match.teams.any?

    respond_to do |format|
      format.html
      format.json { render json: @match }
    end
  end

  def match_info
    match = Match.find(params[:id])
    @match = match.decorate

    @new_players_count = MatchToken.created_recently match

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def new
    @match = Match.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @match = Match.find(params[:id])
    if current_user && current_user.match_tokens.exists?(match_id: @match.id)
      @players = @match.users
      @radiant_team = @match.teams.first
      @dire_team = @match.teams.last
    else
      redirect_to root_path
    end
  end

  def create
    @match = Match.new(match_params)
    @match.creator_id = current_user.id

    respond_to do |format|
      if @match.save
        flash[:success] = 'La partida se creó correctamente.'
        format.html { redirect_to match_path(@match.id) }
      else
        format.html { render 'new' }
      end
    end
  end

  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        flash[:success] =  'La partida se guardó correctamente.'
        redirect_to @match
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.match_tokens.destroy_all
    @match.status = 'canceled'
    @match.save

    respond_to do |format|
      format.html { redirect_to matches_url }
    end
  end

  def leave
    match = Match.find(params[:id])
    if match.leavable?
      if current_user && current_user.match_tokens.exists?(match_id: match.id)
        current_user.leave_match(match)
        flash[:success] = 'Usted salió de la partida.'
      else
        flash[:error] = 'Usted no puede salir de esta partida, no está registrado en ella.'
      end
    else
      flash[:error] = 'La partida se está jugando, usted no puede salir de ella.'
    end
    redirect_to match_path(match)
  end

  def join
    @match = Match.find(params[:id])
    redirect_to user_omniauth_authorize_path(:facebook) if current_user.unjoinable?

    if @match.joinable? && current_user.joinable?
      match_token = MatchToken.new(user_id: current_user.id, match_id: params[:id])
    else
      flash[:error] =  'Usted se encuentra en una partida activa (o no ha autenticado con Facebook).'
      redirect_to match_path(@match)
    end

    match_token.save!

    if @match.start
      flash[:success] =  'La partida se completó contigo, suerte!'
    else
      flash[:success] =  'Usted entró a la partida!'
    end
    redirect_to match_path(@match)
  end

  # TODO: @truenito simplify, refactor, DRY up.
  def establish_match_entities(match)
    @creator = User.find(match.creator_id)
    @radiant_team = match.teams.first
    @radiant_captain_id = @radiant_team.captain_id if match.teams.any?
    @dire_team = match.teams.last
    @dire_captain_id = @dire_team.captain_id if match.teams.any?
    players = match.users.order('match_tokens.created_at ASC')
    @players = players.decorate
    frozen_users_and_stats(match) if match.ended? && !match.users_and_stats.nil?

    return true if @radiant_team.nil?
    if match.ended? && match.users_and_stats.present?
      @radiant_team_avg = Team.rating_average @radiant_team, match
      @dire_team_avg = Team.rating_average @dire_team, match
    else
      @radiant_team_avg = (@radiant_team.users.sum(:rating) / @radiant_team.users.count)
      @dire_team_avg = (@dire_team.users.sum(:rating) / @dire_team.users.count)
    end
  end

  def frozen_users_and_stats(match)
    radiant_team_str_ids = @radiant_team.users.pluck(:id).map!(&:to_s)
    @radiant_team = match.users_and_stats.select { |u| radiant_team_str_ids.include? u['id'] }

    dire_team_str_ids = @dire_team.users.pluck(:id).map!(&:to_s)
    @dire_team = match.users_and_stats.select { |u| dire_team_str_ids.include? u['id'] }
  end

  private

  def match_params
    params.require(:match).permit(:name, :password)
  end
end

app/views/matches/_current_teams.haml
- if @match.ended? && @match.users_and_stats.nil?
  .col-md-12
    #match-info-alert{style: "background-color: black; padding: 20px 30px; margin-top:30px;"}
      %p
        %i.playing Esta partida es antigua (alpha) por tanto los stats de los jugadores (rating/win/loss etc) para esta partida se reflejan al día de hoy y NO representan los stats al tiempo en que se jugó esta partida.
      %p
        %i.playing Para partidas futuras ya se ha implementado esta funcionalidad.
.col-md-12
  %h3.heading-centered{style: 'color: green;'} RADIANT TEAM
  .col-md-3.pull-right{style: 'padding: 0;'}
    %h6{style: 'text-align: right;'}
      Average MMR:
      = @radiant_team_avg
  .col-md-3.pull-right{style: 'padding: 0;'}
    %h6{style: 'text-align: right;'}
      Win:
      +
      = @rating_change[:dire]
      ="/"
      ="-"
      Lose:
      = @rating_change[:radiant]
  .col-md-12.job-listing-full{style: 'padding-top: 0px;'}
    .clearfix
    .job-list-head.clearfix.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
      %ul.job-listings
        - @radiant_team.users.decorate.each do |player|
          %li.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
            .title
              %span.prof-photo
                = link_to(image_tag('avatars/radiant.png'), "/user/#{player.regular_name}")
              %span.designation
                - if player.reported?(@match)
                  = link_to("/user/#{player.regular_name}") do
                    = player.name
                    = image_tag('reported.png', {class: 'mini-badge-icon-circle',  alt: 'Reportó', title: 'Reportó'} )
                - else
                  = link_to(player.name, "/user/#{player.regular_name}")
            .location
              rating:
              = player.rating
            .location{:class => ("captain" if @radiant_team.captain_id == player.id)}= @radiant_team.captain_id == player.id ? "CAPTAIN" : "player"
.col-md-12
  %h3.heading-centered{style: 'color: rgb(181, 62, 76);'} DIRE TEAM
  .col-md-3.pull-right{style: 'padding: 0;'}
    %h6{style: 'text-align: right;'}
      Average MMR:
      = @dire_team_avg
  .col-md-3.pull-right{style: 'padding: 0;'}
    %h6{style: 'text-align: right;'}
      Win:
      +
      = @rating_change[:radiant]
      = "/"
      ="-"
      Lose:
      = @rating_change[:dire]
  .col-md-12.job-listing-full{style: 'padding-top: 0px;'}
    .clearfix
    .job-list-head.clearfix.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
      %ul.job-listings
        - @dire_team.users.decorate.each do |player|
          %li.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
            .title
              %span.prof-photo
                = link_to(image_tag('avatars/dire.png'), "/user/#{player.regular_name}")
              %span.designation
                - if player.reported?(@match)
                  = link_to("/user/#{player.regular_name}") do
                    = player.name
                    = image_tag('reported.png', {class: 'mini-badge-icon-circle',  alt: 'Reportó', title: 'Reportó'} )
                - else
                  = link_to(player.name, "/user/#{player.regular_name}")
            .location
              rating:
              = player.rating
            .location{:class => ("captain" if @dire_team.captain_id == player.id)}= @dire_team.captain_id == player.id ? "CAPTAIN" : "player"

app/views/matches/_frozen_teams.haml
.col-md-12
  %h3.heading-centered{style: 'color: green;'} RADIANT TEAM
  .col-md-3.pull-right{style: 'padding: 0;'}
    %h6{style: 'text-align: right;'}
      Average MMR:
      = @radiant_team_avg
  .col-md-3.pull-right{style: 'padding: 0;'}
    %h6{style: 'text-align: right;'}
      Win:
      +
      = @rating_change[:dire]
      ="/"
      ="-"
      Lose:
      = @rating_change[:radiant]
  .col-md-12.job-listing-full{style: 'padding-top: 0px;'}
    .clearfix
    .job-list-head.clearfix.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
      %ul.job-listings
        - @radiant_team.each do |player|
          %li.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
            .title
              %span.prof-photo
                = link_to(image_tag('avatars/radiant.png'), "/user/#{player['name']}")
              %span.designation
                = link_to("/user/#{player['name']}") do
                  = player['name']
                  = image_tag('reported.png', {class: 'mini-badge-icon-circle',  alt: 'Reportó', title: 'Reportó'} )
                %br
                = player['name']
            .location
              rating:
              = player['rating']
            .location{:class => ("captain" if @radiant_captain_id == player['id'].to_i)}= @radiant_captain_id == player['id'].to_i ? "CAPTAIN" : "player"
            .create= player['status']
            .create= "W:#{player['win_count'].to_i} / L:#{player['lose_count'].to_i}"
.col-md-12
  %h3.heading-centered{style: 'color: rgb(181, 62, 76);'} DIRE TEAM
  .col-md-3.pull-right{style: 'padding: 0;'}
    %h6{style: 'text-align: right;'}
      Average MMR:
      = @dire_team_avg
  .col-md-3.pull-right{style: 'padding: 0;'}
    %h6{style: 'text-align: right;'}
      Win:
      +
      = @rating_change[:radiant]
      = "/"
      ="-"
      Lose:
      = @rating_change[:dire]
  .col-md-12.job-listing-full{style: 'padding-top: 0px;'}
    .clearfix
    .job-list-head.clearfix.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
      %ul.job-listings
        - @dire_team.each do |player|
          %li.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
            .title
              %span.prof-photo
                = link_to(image_tag('avatars/dire.png'), "/user/#{player['name']}")
              %span.designation
                = link_to("/user/#{player['name']}") do
                  = player['name']
                  = image_tag('reported.png', {class: 'mini-badge-icon-circle',  alt: 'Reportó', title: 'Reportó'} )
            .location
              rating:
              = player['rating']
            .location{:class => ("captain" if @dire_captain_id == player['id'].to_i)}= @dire_captain_id == player['id'].to_i ? "CAPTAIN" : "player"
            .create= player['status']
            .create= "W:#{player['win_count'].to_i} / L:#{player['lose_count'].to_i}"

app/views/matches/_match_info.haml
.col-md-12
  .centered
    %h2.heading-centered= @match.name
  .col-md-12.job-listing-full{style: 'padding-top: 0px;'}
    - if current_user
      - if (current_user.id == @match.creator_id) && (@match.status == 'waiting')
        .pull-right= link_to('cancelar partida', match_path(@match), {method: :delete, data: {confirm: 'Estás seguro de que quieres cancelar esta partida? (una vez cancelada no hay vuelta atrás!)'}, style: 'color: rgb(181, 62, 76); font-size: 18px;'})
      - elsif current_user && current_user.match_tokens.exists?(match_id: @match.id) && @match.status == 'playing'
        .pull-right= "  (#{@match.votes_number} reportes)"
        .pull-right.blink_me= link_to "Reportar Resultado ", edit_match_token_path(current_user.match_tokens.find_by_match_id(@match.id)), {style: 'color: green; font-size: 18px; margin-right: 5px;'}
    .clearfix
    .job-list-head.clearfix
      %ul.job-listings
        %li
          .title
            %span.prof-photo
              = image_tag('avatars/dota-logo.png')
            %span.designation
              = @match.name
              %br
                host:
                %i{style: 'color: rgb(181, 62, 76);'}= @creator.name
          .location= "estatus: #{@match.pretty_status}".html_safe
          - if current_user && @match.users.exists?(current_user)
            .location{style: 'text-transform: none !important;'}= "pass: #{@match.password}"
          .location= @match.time_ago
          - if @match.winner_team.nil?
            .create
              %span{style: 'color: rgb(181, 62, 76);'} sin decisión
          - else
            .create= @match.winner_team == 0 ? 'Dire' : 'Radiant'
- unless @new_players_count.nil? || @new_players_count.zero?
  - if @new_players_count == 1
    :javascript
      newPlayerNotification(#{@new_players_count})
  - else
    :javascript
      newPlayersNotification(#{@new_players_count})

:javascript
  function blinker() {
      $('.blink_me').fadeOut(500).fadeIn(1500);
  }

  setInterval(blinker, 2500);

app/views/matches/_player_pool.haml
.col-md-12
  %h3.heading-centered player pool
  - if current_user && !current_user.match_tokens.where(result: nil).any?
    - if !current_user.facebook_authed?
      .pull-right= link_to('Autenticar Facebook', join_match_path(@match.id))
    - elsif @match.status != 'canceled'
      .pull-right= link_to('Entrar al juego +', join_match_path(@match))
  .col-md-12.job-listing-full{style: 'padding-top: 0px;'}
    .clearfix
    .job-list-head.clearfix
      %ul.job-listings
        - @players.each_with_index do |player, i|
          %li
            - if current_user && current_user.id == player.id &&  @match.status == 'waiting'
              .pull-right{style: 'margin-left:15px; text-transform: none !important;'}
                = link_to(image_tag('x-button.png'), leave_match_path(@match.id), {method: 'post', style: 'color: rgb(181, 62, 76);', data: {confirm: 'Estás seguro que deseas salir de esta partida?'}})
            .title
              %span.pool-number
                = i + 1
              %span.designation
                = link_to(player.name, "/user/#{player.regular_name}")
                %br
                = player.real_name
            .location
              rating:
              = player.rating
            .location= "Leaves: #{player.leave_count}"
            .location= player.status
            .create= "W: #{player.win_count} / L: #{player.lose_count}"

app/views/matches/index.haml
.container
  .col-md-12{style: 'margin-top:10px;'}
    .pull-left= link_to 'inicio', root_path, {style: 'color: rgb(181, 62, 76);'}
    .pull-left{style: 'color: rgb(181, 62, 76); padding: 0px 3px'}  >
    .pull-left matches
  .col-md-12
    .centered
      %h2 list of matches
    .col-md-12.job-listing-full
      - if user_signed_in? && current_user.can_create_games?
        .pull-right= link_to 'Crear nuevo juego de liga +', new_match_path
      .clearfix
      .job-list-head.clearfix.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
      - if @matches.any?
        %ul.job-listings
          - @matches.each do |match|
            - if match.canceled?
              %li.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
                .title
                  %span.prof-photo
                    = image_tag('avatars/dota-logo.png')
                  %span.designation
                    = match.name
                .location
                  status:
                  = match.pretty_status
                - if user_signed_in? && match.users.exists?(current_user)
                  .location= "pass: #{match.password}"
                .create= " " + time_ago_in_words(match.created_at)
                - if match.winner_team.nil?
                  .create
                    %span{style: 'color: rgb(181, 62, 76);'} sin decisión
                - else
                  = "winner: "
                  = match.winner_team == false ? 'radiant' : 'dire'
            - else
              = link_to match_path(match) do
                %li.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"}
                  .title
                    %span.prof-photo= image_tag('avatars/dota-logo.png')
                    %span.designation
                      = match.name
                  .location
                    status:
                    = match.pretty_status
                  .create= " " + time_ago_in_words(match.created_at)
                  - if match.winner_team.nil?
                    .create
                      %span{style: 'color: rgb(181, 62, 76);'} sin decisión
                  - else
                    .create
                      = "winner: "
                      = match.winner_team == false ? 'radiant' : 'dire'
      - else
        .centered
          %span= "No se ha jugado ningún match, #{link_to 'TEN EL PRIMERO!', new_match_path}".html_safe

app/views/matches/match_info.js.erb
$('#player-pool').html("<%= escape_javascript(render(:partial => 'player_pool')) %>");
$('#match-data').html("<%= escape_javascript(render(:partial => 'match_info')) %>");
<% if @match.teams.any? %>
  location.reload();
<% end %>

app/views/matches/new.haml
= render 'shared/error_messages', object: @match
%section
.container
  .row.clearfix
    .col-md-6.col-md-offset-3{style: 'padding-top: 20px;'}
    .col-md-6.col-md-offset-3{style: 'padding-top: 20px;'}
      %h2{ style: ' text-align: center;' } create new match
      %hr
        = form_for @match, url: {action: "create"}, html: {class: "nifty_form"} do |f|
          %p
            = f.label :name
            = f.text_field :name, class: 'input-area'
          %p
            = f.label :match_password
            = f.text_field :password, class: 'input-area'
          = f.submit "Create", class: 'input-button'

app/views/matches/show.haml
.container
  .col-md-12{style: 'margin-top:10px;'}
    .pull-left= link_to 'inicio', root_path, {style: 'color: rgb(181, 62, 76);'}
    .pull-left{style: 'color: rgb(181, 62, 76); padding: 0px 3px'}  >
    .pull-left= link_to 'matches', matches_path, {style: 'color: rgb(181, 62, 76);'}
    .pull-left{style: 'color: rgb(181, 62, 76); padding: 0px 3px'}  >
    .pull-left match
  .clearfix
  #match-data
    = render 'match_info'
  - if @match.teams.any?
    - if @match.ended? && !@match.users_and_stats.nil?
      = render 'frozen_teams'
    - else
      = render 'current_teams'
  #player-pool
    = render 'player_pool'

/ Refresh match pool every 5 if waiting for players seconds.
- if @match.status == 'waiting'
  :javascript
    $(document).ready(function () {
        setInterval(refreshPartial, 5000)
    });
    function refreshPartial() {
      $.ajax({
        url: "/match_info?id=#{@match.id}"
     })
    }