config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  # Static pages
  get 'mobile' => 'pages#mobiles'
  get '/report' => 'pages#report'
  get '/contact' => 'pages#contact'
  get '/reglas' => 'pages#rules'
  get '/nosotros' => 'pages#about'
  get '/match_info' => 'matches#match_info'
  get '/live_matches' => 'home#live_matches'

  # Seasons
  get '/seasons/0' => 'pages#season0'

  # User list
  get 'users', to: 'users#index'

  resources :match_tokens, only: [:edit, :update]
  resources :matches do
    member do
      get :join
      post :leave
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks', :registrations => 'registrations' }

  get 'user/:username' => 'users#show', constraints: { username: /[^:]+/ }
  get 'users/:username' => 'users#show', constraints: { username: /[^:]+/ }, as: 'user'
  put 'users/:id' => 'users#update', constraints: { username: /[^:]+/ }
end

app/views/layouts/_footer.haml
.container
  .row.clearfix
    .col-md-12.footer-conts{style: 'text-align: center;'}
      %h3.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "100"} ddl es gratis
      %h5.uppercase.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "200"} Auspiciado por STOMP Machine y la Comunidad de DotA 2 Dominicana.
      %i Las donaciones son opcionales y solo benefician al usuario cosméticamente
      %form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_top"}
        %input{:name => "cmd", :type => "hidden", :value => "_s-xclick"}
          %input{:name => "hosted_button_id", :type => "hidden", :value => "VRFCP26RVLJVA"}
            %input{:alt => "PayPal - The safer, easier way to pay online!", :border => "0", :name => "submit", :src => "https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif", :type => "image"}
              %img{:alt => "", :border => "0", :height => "1", :src => "https://www.paypalobjects.com/en_US/i/scr/pixel.gif", :width => "1"}
      %hr.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "300"}
      %ul.footer-menu.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "200"}
        %li
          = link_to 'INICIO', root_path
        %li
          = link_to('JUEGOS', matches_path)
        %li
          = link_to('JUGADORES', users_path)
        %li
          = link_to('REGLAS', reglas_path, class: 'waiting')
        %li
          = link_to('NOSOTROS', nosotros_path)
        %li
          = mail_to "gabriel@estilopanda.com", 'CONTACTO'
        %li
          = link_to('BETA Season', '/seasons/0', {style: 'color: #7c7c7c;'})

      %p.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "200"}
        \&copy;
        = DateTime.now.strftime("%d/%m/%Y")
        = succeed "." do
          Dominican DotA League, desarrollado por <a target='_blank' href='http://estilopanda.com'>estilopanda.com</a>

app/views/layouts/_general_notifications.haml
- if current_user && current_user.playing?
  :javascript
    rememberReport(#{current_user.current_match_token_id});

app/views/layouts/_login_box.haml
#login-box
  %h3 login
  = render 'shared/flash', flash: flash
  %hr
    = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
      %p{ style: ' text-align: center;' }
        = f.label :email
        = f.email_field :email, autofocus: true, class: 'input-area'
      %p{ style: ' text-align: center;' }
        = f.label :password
        = f.password_field :password, autocomplete: "off", class: 'input-area'
      %p{ style: ' text-align: center;' }
        = f.submit "Log in", class: 'input-button'
      %p{ style: ' text-align: center;' }
        %span No eres un miembro?
        = link_to 'Registrate', new_user_registration_path, {style: 'color: blue !important;'}

app/views/layouts/_main_menu.haml
%nav.navbar-fixed-top.navbar-inverse
  .collapse.navbar-collapse.js-navbar-collapse
    %ul.nav.navbar-nav
      %li.dropdown.mega-dropdown
        = link_to(image_tag('menu-ex.png', width: 130), root_path, {class: 'navbar-brand dropdown-toggle', "data-toggle" => "dropdown", :href => "root_path", style: 'width: 180px;'})
        %ul.dropdown-menu.mega-dropdown-menu
          %li.col-sm-12
            %li= link_to('Inicio', root_path)
          %li.col-sm-3
            %ul
              %li.dropdown-header Liga
              %li.divider
              %li= link_to('Juegos', matches_path)
              %li= link_to('Usuarios', users_path)
              %li= link_to('Season', '/seasons/0')
              %li= link_to('Crear +', new_match_path, class: 'post-job-btn col-md-5 shadow-1', style: 'color: #fff')
              .clearfix
          %li.col-sm-3
            %ul
              %li.dropdown-header Información
              %li.divider
              %li= link_to('Reglas', reglas_path)
              %li= link_to('Nosotros', nosotros_path)
              %li= link_to('Facebook', 'https://www.facebook.com/thestompmachine', target: '_blank')
              %li= mail_to('gabriel@estilopanda.com', 'Contacto')
          %li.col-sm-3
            %ul
              %li.dropdown-header Premios de la Beta Season
              %li.divider
              #menu-carousel.carousel.slide{"data-ride" => "carousel", "data-interval" => "2500"}
                .carousel-inner
                  .item.active
                    = link_to(image_tag('shadow-arcana.png', class: 'img-responsive'), '/seasons/0')
                  .item
                    = link_to(image_tag('lina-arcana.png', class: 'img-responsive'), '/seasons/0')
                  .item
                    = link_to(image_tag('frozen-arcana.png', class: 'img-responsive'), '/seasons/0')
    %ul.nav.navbar-nav.navbar-right
      - if current_user
        %li.dropdown
          = link_to(current_user.name, user_path(current_user.name.downcase), style: 'color: white; margin-right:15px; margin-top: 10px;', class: "dropdown-toggle{'aria-expanded' => 'false', 'data-toggle' => 'dropdown', :href => '#', :role => 'button'}")
          %ul.dropdown-menu.login-menu{:role => "menu"}
            %li= link_to("Rating: #{current_user.rating}", '', {style: 'font-style: italic;'})
            %li.divider
            %li= link_to('Salir', destroy_user_session_path, {style: 'color: rgb(181, 62, 76)', method: :delete})
      - else
        %li
          = link_to('#', {"data-popup" => "facebox", :href => "#login-box", style: 'color: white; margin-right:15px; margin-top: 10px;'}) do
            %span= image_tag('user.png', height: 15, width: 15, style: 'margin-right: 5px; maring-top: -5px;')
            Log In

:javascript
  $(document).ready(function(){
      $(".dropdown").hover(
          function() {
              $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideDown("500");
              $(this).toggleClass('open');
          },
          function() {
              $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideUp("500");
              $(this).toggleClass('open');
          }
      );
  });

app/views/layouts/_stats_sidebar.haml
%h3.pull-left HALL OF FAME
%ul.stat-leaders
  %li.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "200"}
    %a.featured-single{:href => "single.html"}
      %span.featured-data
        %span.designation
          - if @sidebar_stats[:most_captains].nil?
            %span todavía no hay un capitanazo.
          - else
            %span= @sidebar_stats[:most_captains][:user].name
            %br
              %i.bold= "ha sido capitán: #{@sidebar_stats[:most_captains][:count]} veces."
      %span.image-cont
        = image_tag('avatars/captain.png')
  %li.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "200"}
    %a.featured-single{:href => "single.html"}
      %span.featured-data
        %span.designation
          - if @sidebar_stats[:most_creations].nil?
            %span todavía no hay un creador líder.
          - else
            %span= @sidebar_stats[:most_creations][:user].name
            %br
              %i= "ha creado #{@sidebar_stats[:most_creations][:count]} juegos."
      %span.image-cont
        = image_tag('avatars/creator.png')
  - unless @sidebar_stats.nil?
    %li.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "200"}
      %a.featured-single{:href => "single.html"}
        %span.featured-data
          %span.designation
            %span= @sidebar_stats[:most_wins].name
            %br
              %i.bold= "ha ganado: #{@sidebar_stats[:most_wins].win_count} juegos"
        %span.image-cont
          = image_tag('avatars/winner.png')
  - unless @sidebar_stats.nil?
    %li.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "200"}
      %a.featured-single{:href => "single.html"}
        %span.featured-data
          %span.designation
            %span= "ktheory"
            %br
              %i.bold= "ha donado: 55.01 dólares."
        %span.image-cont
          = image_tag('avatars/donatello.png')
  / %li.animated{"data-animation" => "fadeInUp", "data-animation-delay" => "200"}
  /   %a.featured-single{:href => "single.html"}
  /     %span.featured-data
  /       %span.designation
  /         %span= @best_winrate.name
  /         %br
  /           =  "Es el líder de winrate con: #{@best_winrate}."
  /   %span.image-cont
  /     = image_tag('avatars/creator.png')

app/views/layouts/_user_panel.haml
- if current_user
  .user-panel.pull-right
    %span
      %span= image_tag('user.png', height: 15, width: 15, style: 'margin-right: 5px; margin-left: 5px; maring-top: -3px;')
      %s5an= link_to(current_user.name, '#', style: 'color: white;')
      %span{style: 'margin-left:4px;'}= link_to(' salir', destroy_user_session_path, {style: 'color: rgb(181, 62, 76)', method: :delete})
- else
  .user-panel.pull-right
    %span
      = link_to('#', {"data-popup" => "facebox", :href => "#login-box", style: 'color: white;'}) do
        %span= image_tag('user.png', height: 20, width: 20, style: 'margin-right: 5px; maring-top: -5px;')
        %span log in

app/views/layouts/application.haml
!!!
%html{:lang => "en-US"}
  %head
    %meta{:charset => "utf-8"}
      %title Dominican DotA League
      = favicon_link_tag 'favicon.ico'
      %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %meta{:content => "DotA 2, Dominicano, Dota dominicana, dota dominicano, Dota 2 dominicano, dota 2 latino, liga de dota latina, liga de dota dominicana, liga dominicana de dota, dota 2 liga, liga dota 2 dominicana, in houses dota 2, liga de inhouse dominicana, grupo dominicano de dota", :name => "keywords"}
      %meta{:content => "#{request.original_url}", :property => "og:url"}
      %meta{:content => "Dominican DotA League - ddl.do", :property => "og:title"}
      %meta{:content => "website", :property => "og:type"}
      %meta{:content => "http://ddl.do/logo.png", :property => "og:image"}
      %meta{:content => "ddl.do", :property => "og:site_name"}
      - if (params[:controller] == 'matches') && params[:action] == 'show'
        %meta{:content => "Juego del Dominican Gaming League (ddl.do) - Nombre: #{@match.name}, Estatus: #{@match.status}, Creado por: #{@creator.name}, Fecha: #{DateTime.now.strftime("%d/%m/%Y")}.", :name => "description"}
        %meta{:content => "Juego del Dominican Gaming League (ddl.do) - Nombre: #{@match.name}, Estatus: #{@match.status}, Creado por: #{@creator.name}, Fecha: #{DateTime.now.strftime("%d/%m/%Y")}.", :property => "og:description"}
      - else
        %meta{:content => "DDL es una comunidad Dominicana de In-Houses conformada por jugadores competitivos especializados en Defense of the Ancients 2 (DotA 2).", :name => "description"}
        %meta{:content => "DDL es una comunidad Dominicana de In-Houses conformada por jugadores competitivos especializados en Defense of the Ancients 2 (DotA 2).", :property => "og:description"}
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    - if false
      #mask
        #loader
    #login-box
      %h3 login
      %hr
        = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
          %p{ style: ' text-align: center;' }
            = f.label :email
            = f.email_field :email, autofocus: true, class: 'input-area'
          %p{ style: ' text-align: center;' }
            = f.label :password
            = f.password_field :password, autocomplete: "off", class: 'input-area'
          %p{ style: ' text-align: center;' }
            = f.submit "Log in", class: 'input-button'
          %p{ style: ' text-align: center;' }
            %span No eres un miembro?
            = link_to 'Registrate', new_user_registration_path, {style: 'color: blue !important;'}
    / = render('shared/global_announcement')
    = render ('layouts/main_menu')
    - if Rails.env.production?
      %script#cid0020000089726659016{:async => "", "data-cfasync" => "false", :src => "//st.chatango.com/js/gz/emb.js", :style => "width: 250px;height: 300px;"} {"handle":"ddl-web","arch":"js","styles":{"a":"000000","b":100,"c":"FFFFFF","d":"FFFFFF","k":"000000","l":"000000","m":"000000","n":"FFFFFF","p":"10","q":"000000","r":100,"pos":"br","cv":1,"cvfntw":"bold","cvbg":"000000","cvw":122,"cvh":38}}
    #sb-site.wrapper
      .clearfix
      = yield
      .clearfix
      %footer.footer-main
        = render('layouts/footer')
    / ddl General Notifications.
    = render 'shared/flash', flash: flash
    = render('layouts/general_notifications')
    / Analytics (ddl)
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-61803265-1', 'auto');
      ga('send', 'pageview');
    :javascript
      jQuery(document).ready(function($) {
        $('a[data-popup*=facebox]').facebox({
          opacity      : 0.9,
          loadingImage : '',
          closeImage   : ''
        })
      })
    / Banner Slider Js (ddl)
    :javascript
      $('.banner-slider').flexslider({
        animation: "fade",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });
    / Best in Place (ddl)
    :javascript
      $(document).ready(function() {
        jQuery(".best_in_place").best_in_place()
      });

app/views/layouts/home.haml
!!!
%html{:lang => "en-US"}
  %head
    %meta{:charset => "utf-8"}
      %title Dominican DotA League
      = favicon_link_tag 'favicon.ico'
      %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %meta{:content => "DDL es una comunidad Dominicana de In-Houses conformada por jugadores competitivos especializados en Defense of the Ancients 2 (DotA 2).", :name => "description"}
      %meta{:content => "DotA 2, Dominicano, Dota dominicana, dota dominicano, Dota 2 dominicano, dota 2 latino, liga de dota latina, liga de dota dominicana, liga dominicana de dota, dota 2 liga, liga dota 2 dominicana, in houses dota 2, liga de inhouse dominicana, grupo dominicano de dota", :name => "keywords"}
      %meta{:content => "#{request.original_url}", :property => "og:url"}
      %meta{:content => "Dominican DotA League - ddl.do", :property => "og:title"}
      %meta{:content => "DDL es una comunidad Dominicana de In-Houses conformada por jugadores competitivos especializados en Defense of the Ancients 2 (DotA 2).", :property => "og:description"}
      %meta{:content => "website", :property => "og:type"}
      %meta{:content => "http://ddl.do/logo.png", :property => "og:image"}
      %meta{:content => "ddl.do", :property => "og:site_name"}
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    - if false
      #mask
        #loader
    - if Rails.env.production?
      // Chatango
      %script#cid0020000089726659016{:async => "", "data-cfasync" => "false", :src => "//st.chatango.com/js/gz/emb.js", :style => "width: 250px;height: 300px;"} {"handle":"ddl-web","arch":"js","styles":{"a":"000000","b":100,"c":"FFFFFF","d":"FFFFFF","k":"000000","l":"000000","m":"000000","n":"FFFFFF","p":"10","q":"000000","r":100,"pos":"br","cv":1,"cvfntw":"bold","cvbg":"000000","cvw":122,"cvh":38}}
    = render('shared/global_announcement')
    .clearfix
    #sb-site.wrapper
      = yield
      .clearfix
      %footer.footer-main
        = render('layouts/footer')
    / ddl General Notifications.
    = render('layouts/general_notifications')
    = render 'shared/flash', flash: flash
    - if Rails.env.production?
      / ddl Google Analytics.
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-61803265-1', 'auto');
        ga('send', 'pageview');
      / ddl Loading gif.
    :javascript
      jQuery(document).ready(function($) {
        $('a[data-popup*=facebox]').facebox({
          opacity      : 0.9,
          loadingImage : '',
          closeImage   : ''
        })
      })
    / ddl Banner Slider Js.
    :javascript
      $('.banner-slider').flexslider({
        animation: "fade",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });
    / ddl Menu
    :javascript
      $(document).ready(function(){
          $(".dropdown").hover(
              function() {
                  $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideDown("500");
                  $(this).toggleClass('open');
              },
              function() {
                  $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideUp("500");
                  $(this).toggleClass('open');
              }
          );
      });